# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Kyria v1 nice_nano_v2 with displays'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["kyria_left","kyria_right"]'
      alphas: '["qwerty"]'
      extras: '["colemak","colemakdhk","dvorak"]'
      tap: '["qwerty"]'
      layers: '["flip"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
