# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build kyria_v1 with nice_nano_v2 and displays'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["kyria_left","kyria_right"]'
      alphas: '["qwerty"]'
      extra: '["colemak"]'
      tap: '["qwerty"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
